# Generated by Django 5.2.9 on 2026-02-11 15:43

import django.db.models.deletion
import openplan.utils.fields
import uuid
import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoelCategorie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('naam', models.CharField(help_text='Naam van de doelcategorie.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Doelcategorie',
                'verbose_name_plural': 'Doelcategorieen',
            },
        ),
        migrations.CreateModel(
            name='InstrumentCategorie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('naam', models.CharField(help_text='Naam van de instrumentcategorie.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Instrumentcategorie',
                'verbose_name_plural': 'Instrumentcategorieen',
            },
        ),
        migrations.CreateModel(
            name='OverkoepelendPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('titel', models.CharField(help_text='Titel van het overkoepelende plan.', max_length=255)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het overkoepelende plan.', max_length=20)),
                ('medewerker', openplan.utils.fields.URNField(blank=True, help_text='URN naar de medewerker in het HR-systeem.', max_length=255)),
            ],
            options={
                'verbose_name': 'Overkoepelend plan',
                'verbose_name_plural': 'Overkoepelende plannen',
            },
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('persoonsprofiel', openplan.utils.fields.URNField(blank=True, help_text='URN naar het persoonsprofiel (alleen voor primaire personen verplicht).', max_length=255)),
                ('klant', openplan.utils.fields.URNField(blank=True, help_text='URN naar de Klant (verplicht voor primaire personen, optioneel voor secundaire).', max_length=255)),
                ('bsn', vng_api_common.fields.BSNField(blank=True, help_text='BSN voor BRP-koppeling (verplicht voor primaire personen, optioneel voor secundaire).', max_length=9)),
            ],
            options={
                'verbose_name': 'Persoon',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pip', 'Persoonlijk plan inburgering en perticipatie'), ('werk', 'Werk'), ('inkomen', 'Inkomen')], help_text='Het type plan.', max_length=50)),
            ],
            options={
                'verbose_name': 'Plantype',
                'verbose_name_plural': 'Plantypen',
            },
        ),
        migrations.CreateModel(
            name='RelatieType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('naam', models.CharField(help_text='Naam van het relatietype', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Relatietype',
                'verbose_name_plural': 'Relatietypen',
            },
        ),
        migrations.CreateModel(
            name='DoelType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('doel_type', models.CharField(choices=[('hoofddoel', 'Hoofddoel'), ('subdoel', 'Subdoel')], help_text='Het type doel.', max_length=50)),
                ('categorieen', models.ManyToManyField(help_text='Categorieën waaraan dit doeltype gekoppeld is.', related_name='doeltypes', to='plannen.doelcategorie')),
            ],
            options={
                'verbose_name': 'Doeltype',
                'verbose_name_plural': 'Doeltypen',
            },
        ),
        migrations.CreateModel(
            name='Doel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het doel.', max_length=20)),
                ('titel', models.CharField(help_text='Titel van het doel.', max_length=255)),
                ('beschrijving', models.TextField(blank=True, help_text='Beschrijving van het doel.', max_length=1000)),
                ('startdatum', models.DateTimeField(db_index=True, help_text='Startdatum van het doel.')),
                ('einddatum', models.DateTimeField(blank=True, help_text='Einddatum van het doel.', null=True)),
                ('resultaat', models.CharField(blank=True, choices=[('behaald', 'Behaald'), ('gefaald', 'Gefaald')], help_text='Resultaat van het doel.', max_length=20)),
                ('toelichting_resultaat', models.TextField(blank=True, help_text='Toelichting bij het resultaat van het doel.', max_length=1000)),
                ('hoofd_doel', models.ForeignKey(blank=True, help_text='Optionele koppeling naar een bovenliggend doel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdoelen', to='plannen.doel')),
                ('doeltype', models.ForeignKey(help_text='Type van het doel', on_delete=django.db.models.deletion.PROTECT, related_name='doelen', to='plannen.doeltype')),
                ('persoon', models.ForeignKey(help_text='Het primaire persoon bij wie dit doel hoort.', on_delete=django.db.models.deletion.CASCADE, related_name='doelen', to='plannen.persoon')),
            ],
            options={
                'verbose_name': 'Doel',
                'verbose_name_plural': 'Doelen',
                'ordering': ('-startdatum',),
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('training', 'Training'), ('coaching', 'Coaching'), ('financiele_ondersteuning', 'Financiele ondersteuning')], help_text='Het type instrument.', max_length=50)),
                ('categorieen', models.ManyToManyField(help_text='Categorieën waaraan dit instrumenttype gekoppeld is.', related_name='instrumenttypes', to='plannen.instrumentcategorie')),
            ],
            options={
                'verbose_name': 'Instrumenttype',
                'verbose_name_plural': 'Instrumenttypen',
            },
        ),
        migrations.CreateModel(
            name='Ontwikkelwens',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het ontwikkelwens.', max_length=20)),
                ('titel', models.CharField(help_text='Titel van het ontwikkelwens.', max_length=255)),
                ('beschrijving', models.TextField(blank=True, help_text='Beschrijving van het ontwikkelwens.', max_length=1000)),
                ('startdatum', models.DateTimeField(db_index=True, help_text='Startdatum van het ontwikkelwens.')),
                ('einddatum', models.DateTimeField(blank=True, help_text='Einddatum van het ontwikkelwens.', null=True)),
                ('resultaat', models.CharField(blank=True, choices=[('behaald', 'Behaald'), ('gefaald', 'Gefaald')], help_text='Resultaat van het ontwikkelwens.', max_length=20)),
                ('doel', models.ForeignKey(help_text='Het doel waaraan dit ontwikkelwens gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='ontwikkelwensen', to='plannen.doel')),
                ('doel_categorieen', models.ManyToManyField(help_text='Categorieën waaraan dit ontwikkelwens gekoppeld is.', related_name='ontwikkelwensen', to='plannen.doelcategorie')),
            ],
            options={
                'verbose_name': 'Ontwikkelwens',
                'verbose_name_plural': 'Ontwikkelwensen',
                'ordering': ('-startdatum',),
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het instrument.', max_length=20)),
                ('titel', models.CharField(help_text='Titel van het instrument.', max_length=255)),
                ('startdatum', models.DateTimeField(db_index=True, help_text='Startdatum van het instrument.')),
                ('einddatum', models.DateTimeField(blank=True, help_text='Einddatum van het instrument.', null=True)),
                ('resultaat', models.CharField(blank=True, choices=[('behaald', 'Behaald'), ('gefaald', 'Gefaald')], help_text='Resultaat van het instrument.', max_length=20)),
                ('product', openplan.utils.fields.URNField(blank=True, help_text='URN naar de bijbehorende product in het productsysteem.', max_length=255)),
                ('zaak', openplan.utils.fields.URNField(blank=True, help_text='URN naar het bijbehorende zaak in het zaaksysteem.', max_length=255)),
                ('doelen', models.ManyToManyField(blank=True, help_text='Doelen waaraan dit instrument gekoppeld is.', related_name='instrumenten', to='plannen.doel')),
                ('instrument_categorieen', models.ManyToManyField(help_text='Categorieen van het instrument.', related_name='instrumenten', to='plannen.instrumentcategorie')),
                ('instrumenttype', models.ForeignKey(help_text='Het type instrument dat hier wordt toegepast.', on_delete=django.db.models.deletion.PROTECT, to='plannen.instrumenttype')),
                ('ontwikkelwensen', models.ManyToManyField(blank=True, help_text='Ontwikkelwensen waaraan dit instrument gekoppeld is.', related_name='instrumenten', to='plannen.ontwikkelwens')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instrumenten',
                'ordering': ('-startdatum',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het plan.', max_length=20)),
                ('fase', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Fase van het plan.', max_length=20)),
                ('titel', models.CharField(help_text='Titel van het plan.', max_length=255)),
                ('notitie', models.TextField(blank=True, help_text='Notitie bij het plan.', max_length=1000)),
                ('startdatum', models.DateTimeField(db_index=True, help_text='Startdatum van het plan.')),
                ('einddatum', models.DateTimeField(blank=True, help_text='Einddatum van het plan.', null=True)),
                ('reden_einde', models.TextField(blank=True, help_text='Reden waarom het plan is beëindigd.', max_length=1000)),
                ('zaak', openplan.utils.fields.URNField(blank=True, help_text='URN naar de bijbehorende zaak in het zaaksysteem.', max_length=255)),
                ('domeinregister', openplan.utils.fields.URNField(blank=True, help_text='URN naar het domeinregister voor dit plan.', max_length=255)),
                ('medewerker', openplan.utils.fields.URNField(blank=True, help_text='URN naar de medewerker in het HR-systeem.', max_length=255)),
                ('overkoepelend_plan', models.ForeignKey(help_text='Het overkoepelend plan waar dit plan deel van uitmaakt.', on_delete=django.db.models.deletion.PROTECT, related_name='plannen', to='plannen.overkoepelendplan')),
                ('plantype', models.ForeignKey(help_text='Type van het plan.', on_delete=django.db.models.deletion.PROTECT, to='plannen.plantype')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plannen',
                'ordering': ('-startdatum',),
            },
        ),
        migrations.AddField(
            model_name='doel',
            name='plannen',
            field=models.ManyToManyField(help_text='Plannen waaraan dit doel gekoppelt is.', related_name='doelen', to='plannen.plan'),
        ),
        migrations.CreateModel(
            name='Contactmoment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('afgerond', 'Afgerond'), ('geannuleerd', 'Geannuleerd')], default='actief', help_text='Status van het contactmoment.', max_length=20)),
                ('toelichting_status', models.TextField(blank=True, help_text='Toelichting bij de status van het contactmoment.', max_length=1000)),
                ('datum', models.DateTimeField(db_index=True, help_text='Startdatum van het contactmoment.')),
                ('notitie', models.TextField(blank=True, help_text='Notitie bij het contactmoment.', max_length=1000)),
                ('persoonsprofiel', openplan.utils.fields.URNField(blank=True, help_text='URL naar het persoonsprofiel (alleen voor primaire personen verplicht).', max_length=255)),
                ('plan', models.ForeignKey(help_text='Het plan waarbij dit contactmoment hoort.', on_delete=django.db.models.deletion.CASCADE, related_name='contactmomenten', to='plannen.plan')),
            ],
            options={
                'verbose_name': 'Contactmoment',
                'verbose_name_plural': 'Contactmomenten',
                'ordering': ('-datum',),
            },
        ),
        migrations.CreateModel(
            name='Relatie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unieke resource identifier (UUID4).', primary_key=True, serialize=False)),
                ('gerelateerde_persoon', models.ForeignKey(help_text='De persoon naar wie de relatie gericht is.', on_delete=django.db.models.deletion.CASCADE, related_name='relaties_naar', to='plannen.persoon')),
                ('persoon', models.ForeignKey(help_text='De primaire persoon van wie de relatie is.', on_delete=django.db.models.deletion.CASCADE, related_name='relaties_vanuit', to='plannen.persoon')),
                ('relatietype', models.ForeignKey(help_text='Het type relatie tussen de betrokken personen.', on_delete=django.db.models.deletion.PROTECT, to='plannen.relatietype')),
            ],
            options={
                'verbose_name': 'Relatie',
                'verbose_name_plural': 'Relaties',
                'constraints': [models.UniqueConstraint(fields=('persoon', 'gerelateerde_persoon', 'relatietype'), name='unieke_relaties_tussen_personen')],
            },
        ),
    ]
