# Generated by Django 5.2.9 on 2025-12-16 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoelCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze categorie.', unique=True)),
                ('naam', models.CharField(help_text='Naam van de doelcategorie.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Doelcategorie',
                'verbose_name_plural': 'Doelcategorieën',
            },
        ),
        migrations.CreateModel(
            name='DoelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('type', models.CharField(choices=[('Hoofddoel', 'Hoofddoel'), ('Subdoel', 'Subdoel'), ('Ontwikkelwens', 'Ontwikkelwens')], help_text='De unieke naam van dit doeltype.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Doeltype',
                'verbose_name_plural': 'Doeltypen',
            },
        ),
        migrations.CreateModel(
            name='InstrumentCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze categorie.', unique=True)),
                ('naam', models.CharField(help_text='Naam van de instrumentcategorie.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Instrumentcategorie',
                'verbose_name_plural': 'Instrumentcategorieën',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('type', models.CharField(choices=[('Training', 'Training'), ('Coaching', 'Coaching'), ('Financiële ondersteuning', 'Financiële ondersteuning')], help_text='Het type instrument.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Instrumenttype',
                'verbose_name_plural': 'Instrumenttypen',
            },
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('persoonsprofiel_url', models.URLField(blank=True, help_text='URL naar het persoonsprofiel (alleen voor primaire personen verplicht).')),
                ('open_klant_url', models.URLField(blank=True, help_text='URL naar Open Klant (verplicht voor primaire personen, optioneel voor secundaire).')),
                ('bsn', models.CharField(blank=True, help_text='BSN voor BRP-koppeling (verplicht voor primaire personen, optioneel voor secundaire).', max_length=9)),
            ],
            options={
                'verbose_name': 'Persoon',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plannen',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('type', models.CharField(choices=[('PIP', 'Persoonlijk plan inburgering en perticipatie'), ('Werk', 'Werk'), ('Inkomen', 'Inkomen')], help_text='Het type plan.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Plantype',
                'verbose_name_plural': 'Plantypen',
            },
        ),
        migrations.CreateModel(
            name='RelatieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('naam', models.CharField(help_text='Naam van het relatietype', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Relatietype',
                'verbose_name_plural': 'Relatietypen',
            },
        ),
        migrations.CreateModel(
            name='Doel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('hoofd_doel', models.ForeignKey(blank=True, help_text='Optionele koppeling naar een bovenliggend doel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdoelen', to='plannen.doel')),
                ('doeltype', models.ForeignKey(help_text='Type van het doel', on_delete=django.db.models.deletion.PROTECT, related_name='doelen', to='plannen.doeltype')),
                ('persoon', models.ForeignKey(help_text='Het primaire persoon bij wie dit doel hoort.', on_delete=django.db.models.deletion.CASCADE, related_name='doelen', to='plannen.persoon')),
                ('plan', models.ForeignKey(help_text='Het plan waarbij dit doel hoort.', on_delete=django.db.models.deletion.CASCADE, related_name='doelen', to='plannen.plan')),
            ],
            options={
                'verbose_name': 'Doel',
                'verbose_name_plural': 'Doelen',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('doel', models.ForeignKey(help_text='Het doel waaraan dit instrument gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='instrumenten', to='plannen.doel')),
                ('instrumenttype', models.ForeignKey(help_text='Het type instrument dat hier wordt toegepast.', on_delete=django.db.models.deletion.PROTECT, to='plannen.instrumenttype')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instrumenten',
            },
        ),
        migrations.CreateModel(
            name='Contactmoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('plan', models.ForeignKey(help_text='Het plan waarbij dit contactmoment hoort.', on_delete=django.db.models.deletion.CASCADE, related_name='contactmomenten', to='plannen.plan')),
            ],
            options={
                'verbose_name': 'Contactmoment',
                'verbose_name_plural': 'Contactmomenten',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='plantype',
            field=models.ForeignKey(help_text='Type van het plan.', on_delete=django.db.models.deletion.PROTECT, to='plannen.plantype'),
        ),
        migrations.CreateModel(
            name='Relatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('gerelateerde_persoon', models.ForeignKey(help_text='De persoon naar wie de relatie gericht is.', on_delete=django.db.models.deletion.CASCADE, related_name='relaties_naar', to='plannen.persoon')),
                ('persoon', models.ForeignKey(help_text='De primaire persoon van wie de relatie is.', on_delete=django.db.models.deletion.CASCADE, related_name='relaties_vanuit', to='plannen.persoon')),
                ('relatietype', models.ForeignKey(help_text='Het type relatie tussen de betrokken personen.', on_delete=django.db.models.deletion.PROTECT, to='plannen.relatietype')),
            ],
            options={
                'verbose_name': 'Relatie',
                'verbose_name_plural': 'Relaties',
                'constraints': [models.UniqueConstraint(fields=('persoon', 'gerelateerde_persoon', 'relatietype'), name='unieke_relaties_tussen_personen')],
            },
        ),
    ]
