# Generated by Django 5.2.9 on 2026-01-21 11:04

import django.db.models.deletion
import openplan.utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('plannen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.')),
                ('zaak', openplan.utils.fields.URNField(blank=True, help_text='URN naar de bijbehorende zaak in het zaaksysteem.', max_length=255)),
                ('domeinregister', openplan.utils.fields.URNField(blank=True, help_text='URN naar het domeinregister voor dit plan.', max_length=255)),
                ('medewerker', openplan.utils.fields.URNField(blank=True, help_text='URN naar de medewerker in het HR-systeem.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plan',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "plannen_planevent" ("domeinregister", "id", "medewerker", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plantype_id", "uuid", "zaak") VALUES (NEW."domeinregister", NEW."id", NEW."medewerker", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plantype_id", NEW."uuid", NEW."zaak"); RETURN NULL;', hash='d95c130d45e3723ffeb8ef146a79c0d0f6e5d85b', operation='INSERT', pgid='pgtrigger_insert_insert_3c999', table='plannen_plan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plan',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "plannen_planevent" ("domeinregister", "id", "medewerker", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plantype_id", "uuid", "zaak") VALUES (NEW."domeinregister", NEW."id", NEW."medewerker", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plantype_id", NEW."uuid", NEW."zaak"); RETURN NULL;', hash='16576b77113dc007dc8df6995f6def92220461c0', operation='UPDATE', pgid='pgtrigger_update_update_376ec', table='plannen_plan', when='AFTER')),
        ),
        migrations.AddField(
            model_name='planevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='planevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='plannen.plan'),
        ),
        migrations.AddField(
            model_name='planevent',
            name='plantype',
            field=models.ForeignKey(db_constraint=False, help_text='Type van het plan.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.plantype'),
        ),
    ]
