# Generated by Django 5.2.9 on 2026-01-22 13:12

import django.db.models.deletion
import openplan.utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('plannen', '0002_planevent_plan_insert_insert_plan_update_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersoonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)')),
                ('persoonsprofiel', openplan.utils.fields.URNField(blank=True, help_text='URN naar het persoonsprofiel (alleen voor primaire personen verplicht).', max_length=255)),
                ('klant', openplan.utils.fields.URNField(blank=True, help_text='URN naar de Klant (verplicht voor primaire personen, optioneel voor secundaire).', max_length=255)),
                ('bsn', vng_api_common.fields.BSNField(blank=True, help_text='BSN voor BRP-koppeling (verplicht voor primaire personen, optioneel voor secundaire).', max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatieEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatieTypeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.')),
                ('naam', models.CharField(help_text='Naam van het relatietype', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "plannen_doelevent" ("doeltype_id", "hoofd_doel_id", "id", "persoon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "uuid") VALUES (NEW."doeltype_id", NEW."hoofd_doel_id", NEW."id", NEW."persoon_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plan_id", NEW."uuid"); RETURN NULL;', hash='1352fa64a94a917bb0685ddf43ae0da11742ab3e', operation='INSERT', pgid='pgtrigger_insert_insert_ee368', table='plannen_doel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "plannen_doelevent" ("doeltype_id", "hoofd_doel_id", "id", "persoon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "uuid") VALUES (NEW."doeltype_id", NEW."hoofd_doel_id", NEW."id", NEW."persoon_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plan_id", NEW."uuid"); RETURN NULL;', hash='5ceb337bd3d8c746daa01d97c3df7b83de7afe1d', operation='UPDATE', pgid='pgtrigger_update_update_e5ff1', table='plannen_doel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='persoon',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "plannen_persoonevent" ("bsn", "id", "klant", "persoonsprofiel", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."bsn", NEW."id", NEW."klant", NEW."persoonsprofiel", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."uuid"); RETURN NULL;', hash='835342b40622235895cd508a60503ec9f2263c7c', operation='INSERT', pgid='pgtrigger_insert_insert_6670b', table='plannen_persoon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='persoon',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "plannen_persoonevent" ("bsn", "id", "klant", "persoonsprofiel", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."bsn", NEW."id", NEW."klant", NEW."persoonsprofiel", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."uuid"); RETURN NULL;', hash='cd4de8cacce969adf61dc24bbe0bb78dbfe3d265', operation='UPDATE', pgid='pgtrigger_update_update_d1dd2', table='plannen_persoon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='relatie',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "plannen_relatieevent" ("gerelateerde_persoon_id", "id", "persoon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relatietype_id", "uuid") VALUES (NEW."gerelateerde_persoon_id", NEW."id", NEW."persoon_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relatietype_id", NEW."uuid"); RETURN NULL;', hash='a06ac88c6b6a25964e3ba81bc1a9eaa4aa992c33', operation='INSERT', pgid='pgtrigger_insert_insert_5e869', table='plannen_relatie', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='relatie',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "plannen_relatieevent" ("gerelateerde_persoon_id", "id", "persoon_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relatietype_id", "uuid") VALUES (NEW."gerelateerde_persoon_id", NEW."id", NEW."persoon_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relatietype_id", NEW."uuid"); RETURN NULL;', hash='3a9c025012c9c379387e396f24ca5b434a70567e', operation='UPDATE', pgid='pgtrigger_update_update_c5bda', table='plannen_relatie', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='relatietype',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "plannen_relatietypeevent" ("id", "naam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."id", NEW."naam", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."uuid"); RETURN NULL;', hash='740cb19f82add0cd36e44ca72cb8e21283b8bb59', operation='INSERT', pgid='pgtrigger_insert_insert_0a359', table='plannen_relatietype', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='relatietype',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "plannen_relatietypeevent" ("id", "naam", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."id", NEW."naam", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."uuid"); RETURN NULL;', hash='87a546ae4ad9d67d1efa9317152546d4fc0917a4', operation='UPDATE', pgid='pgtrigger_update_update_13648', table='plannen_relatietype', when='AFTER')),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='doeltype',
            field=models.ForeignKey(db_constraint=False, help_text='Type van het doel', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.doeltype'),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='hoofd_doel',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optionele koppeling naar een bovenliggend doel.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.doel'),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='persoon',
            field=models.ForeignKey(db_constraint=False, help_text='Het primaire persoon bij wie dit doel hoort.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.persoon'),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='plannen.doel'),
        ),
        migrations.AddField(
            model_name='doelevent',
            name='plan',
            field=models.ForeignKey(db_constraint=False, help_text='Het plan waarbij dit doel hoort.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.plan'),
        ),
        migrations.AddField(
            model_name='persoonevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='persoonevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='plannen.persoon'),
        ),
        migrations.AddField(
            model_name='relatieevent',
            name='gerelateerde_persoon',
            field=models.ForeignKey(db_constraint=False, help_text='De persoon naar wie de relatie gericht is.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.persoon'),
        ),
        migrations.AddField(
            model_name='relatieevent',
            name='persoon',
            field=models.ForeignKey(db_constraint=False, help_text='De primaire persoon van wie de relatie is.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.persoon'),
        ),
        migrations.AddField(
            model_name='relatieevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='relatieevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='plannen.relatie'),
        ),
        migrations.AddField(
            model_name='relatieevent',
            name='relatietype',
            field=models.ForeignKey(db_constraint=False, help_text='Het type relatie tussen de betrokken personen.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='plannen.relatietype'),
        ),
        migrations.AddField(
            model_name='relatietypeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='relatietypeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='plannen.relatietype'),
        ),
    ]
